version: 2

models:
  - name: dim_movies
    description: Dimension table for cleansed movie metadata
    columns:
      - name: movie_id
        description: Primary Key of the movie
        tests:
          - not_null

      - name: movie_title
        description: Standardized movie title
        tests:
          - not_null

      - name: genre_array
        description: List of genres in array format

      - name: genre
        description: Raw genre string from sources
